### Suche nach vorhandenem Titel
GET {{restUrl}}?titel=Mockingbird
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

### Suche nach nicht-vorhandenem Titel
GET {{restUrl}}?titel=KeinSong
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

### Suche nach musikLabel
GET {{restUrl}}?musikLabel=Polar Music
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}
